FROM --platform=linux/amd64 ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libtermkey-dev ncurses-dev

COPY . /repo
WORKDIR /repo
RUN ./configure
RUN make -j8
